version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit:3.2.12-ubuntu20
    ports:
      - "29418:29418"
      - "3200:8080"
    volumes:
      - ./external/gerrit/etc:/var/gerrit/etc
      - ./external/gerrit/git:/var/gerrit/git
      - ./external/gerrit/db:/var/gerrit/db
      - ./external/gerrit/index:/var/gerrit/index
      - ./external/gerrit/cache:/var/gerrit/cache
      - ./plugins:/var/gerrit/plugins
    environment:
      - CANONICAL_WEB_URL=http://gerrit.test
    # command: initls
